In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'C:\code.folder\New folder\DATA\sample_weather_data.csv')

In [3]:
data

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),Rainfall (mm),Condition,UV Index
0,2024-01-01,27.5,83.9,14.4,0.2,Cloudy,2
1,2024-01-02,24.3,77.0,5.6,0.3,Rainy,7
2,2024-01-03,28.2,74.9,4.3,0.6,Stormy,1
3,2024-01-04,32.6,75.1,13.0,0.4,Sunny,10
4,2024-01-05,23.8,58.0,3.4,0.4,Foggy,6
...,...,...,...,...,...,...,...
195,2024-07-14,26.9,45.9,8.6,0.1,Cloudy,1
196,2024-07-15,20.6,45.9,5.3,3.0,Foggy,3
197,2024-07-16,25.8,72.5,14.8,1.2,Cloudy,1
198,2024-07-17,25.3,77.3,9.1,1.5,Foggy,6
199,2024-07-18,19.3,69.2,3.6,1.2,Sunny,1

In [4]:
data.head()

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),Rainfall (mm),Condition,UV Index
0,2024-01-01,27.5,83.9,14.4,0.2,Cloudy,2
1,2024-01-02,24.3,77.0,5.6,0.3,Rainy,7
2,2024-01-03,28.2,74.9,4.3,0.6,Stormy,1
3,2024-01-04,32.6,75.1,13.0,0.4,Sunny,10
4,2024-01-05,23.8,58.0,3.4,0.4,Foggy,6

In [5]:
data.shape

(200, 7)

In [6]:
data.index

RangeIndex(start=0, stop=200, step=1)

In [7]:
data.columns

Index(['Date', 'Temperature (C)', 'Humidity (%)', 'Wind Speed (km/h)',
       'Rainfall (mm)', 'Condition', 'UV Index'],
      dtype='object')

In [8]:
data.dtypes

Date                  object
Temperature (C)      float64
Humidity (%)         float64
Wind Speed (km/h)    float64
Rainfall (mm)        float64
Condition             object
UV Index               int64
dtype: object

In [5]:
data['Condition'].unique()

array(['Cloudy', 'Rainy', 'Stormy', 'Sunny', 'Foggy'], dtype=object)

In [6]:
data['Condition'].nunique()

5

In [19]:
data.nunique()

Date                 200
Temperature (C)      122
Humidity (%)         164
Wind Speed (km/h)    116
Rainfall (mm)         58
Condition              5
UV Index              11
dtype: int64

In [25]:
data.count()

Date                 200
Temperature (C)      200
Humidity (%)         200
Wind Speed (km/h)    200
Rainfall (mm)        200
Condition            200
UV Index             200
dtype: int64

In [23]:
data['Condition'].value_counts()

Condition
Cloudy    46
Sunny     42
Rainy     41
Foggy     40
Stormy    31
Name: count, dtype: int64

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               200 non-null    object
 1   Temperature (C)    200 non-null    float64
 2   Humidity (%)       200 non-null    float64
 3   Wind Speed (km/h)  200 non-null    float64
 4   Rainfall (mm)      200 non-null    float64
 5   Condition          200 non-null    object
 6   UV Index           200 non-null    int64
dtypes: float64(4), int64(1), object(2)
memory usage: 11.1+ KB

In [35]:

data[data.Condition == 'Sunny'].head(2)

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),Rainfall (mm),Condition,UV Index
3,2024-01-04,32.6,75.1,13.0,0.4,Sunny,10
11,2024-01-12,22.7,65.1,14.9,8.1,Sunny,9

In [12]:
#data.groupby('Condition').get_group('Cloudy')

In [18]:
data[data['Wind Speed (km/h)'] >= 14].head(2)

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),Rainfall (mm),Condition,UV Index
0,2024-01-01,27.5,83.9,14.4,0.2,Cloudy,2
5,2024-01-06,23.8,54.7,14.4,0.7,Rainy,1

In [ ]:
#data.isnull()
data.isnull().sum()

Date                 0
Temperature (C)      0
Humidity (%)         0
Wind Speed (km/h)    0
Rainfall (mm)        0
Condition            0
UV Index             0
dtype: int64

In [68]:
#rename column name 
#data.rename (columns = {'Rainfall (mm)': 'rainfall (barish)'},inplace=False) # when inplace is false it will not change the original data
data.rename (columns = {'rainfall (barish)': 'rainrate'},inplace=True) # when inplace is true it will change the original data

In [69]:
data.head()

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),rainrate,Condition,UV Index
0,2024-01-01,27.5,83.9,14.4,0.2,Cloudy,2
1,2024-01-02,24.3,77.0,5.6,0.3,Rainy,7
2,2024-01-03,28.2,74.9,4.3,0.6,Stormy,1
3,2024-01-04,32.6,75.1,13.0,0.4,Sunny,10
4,2024-01-05,23.8,58.0,3.4,0.4,Foggy,6

In [73]:
#mean

data.rainrate.mean()

np.float64(1.9494999999999998)

In [ ]:
# standard deviation
data.rainrate.std()

np.float64(1.9201391673809878)

In [74]:
# variance
data.rainrate.var()

np.float64(3.6869344221105527)

In [75]:
data["Condition"].value_counts()

Condition
Cloudy    46
Sunny     42
Rainy     41
Foggy     40
Stormy    31
Name: count, dtype: int64

In [76]:
data[data["Condition"] == "Sunny"]

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),rainrate,Condition,UV Index
3,2024-01-04,32.6,75.1,13.0,0.4,Sunny,10
11,2024-01-12,22.7,65.1,14.9,8.1,Sunny,9
15,2024-01-16,22.2,79.8,7.8,4.0,Sunny,2
16,2024-01-17,19.9,84.5,9.4,3.4,Sunny,1
20,2024-01-21,32.3,68.9,8.8,5.3,Sunny,7
24,2024-01-25,22.3,54.3,14.3,2.9,Sunny,6
35,2024-02-05,18.9,44.3,14.8,1.3,Sunny,2
45,2024-02-15,21.4,53.5,10.9,2.3,Sunny,0
56,2024-02-26,20.8,67.5,8.9,5.6,Sunny,0
64,2024-03-05,29.1,61.0,0.8,0.5,Sunny,0
67,2024-03-08,30.0,77.9,15.0,3.4,Sunny,0
70,2024-03-11,26.8,42.3,11.5,0.9,Sunny,3
71,2024-03-12,32.7,42.0,14.2,4.2,Sunny,10
74,2024-03-15,11.9,63.7,6.8,1.2,Sunny,4
75,2024-03-16,29.1,44.9,1.9,0.9,Sunny,10
89,2024-03-30,27.6,48.1,8.4,0.8,Sunny,5
91,2024-04-01,29.8,72.1,6.1,3.2,Sunny,2
93,2024-04-03,23.4,69.3,0.4,1.5,Sunny,10
100,2024-04-10,17.9,87.1,5.3,0.1,Sunny,2
105,2024-04-15,27.0,43.5,5.2,3.4,Sunny,5
109,2024-04-19,24.6,74.2,9.3,1.0,Sunny,2
117,2024-04-27,19.2,74.8,14.7,1.6,Sunny,1
128,2024-05-08,25.5,58.6,2.7,1.4,Sunny,1
133,2024-05-13,27.4,61.4,2.6,1.7,Sunny,10
141,2024-05-21,31.5,84.8,6.9,2.7,Sunny,8
146,2024-05-26,18.8,56.0,0.6,8.4,Sunny,7
150,2024-05-30,26.3,71.6,13.1,4.1,Sunny,4
151,2024-05-31,26.7,62.4,13.8,1.5,Sunny,9
152,2024-06-01,21.6,54.7,0.9,1.8,Sunny,1
153,2024-06-02,26.2,56.4,4.2,1.0,Sunny,5
154,2024-06-03,26.5,73.6,12.1,0.1,Sunny,4
158,2024-06-07,19.0,44.6,5.6,0.8,Sunny,7
173,2024-06-22,26.7,81.1,3.6,0.9,Sunny,10
175,2024-06-24,29.1,44.1,5.7,2.0,Sunny,8
177,2024-06-26,32.3,89.3,4.8,2.2,Sunny,8
178,2024-06-27,23.7,58.7,3.2,0.4,Sunny,4
182,2024-07-01,19.6,89.3,8.9,0.2,Sunny,5
184,2024-07-03,23.9,58.8,11.8,1.4,Sunny,4
186,2024-07-05,27.4,78.9,1.3,0.1,Sunny,9
190,2024-07-09,22.8,45.6,6.5,0.5,Sunny,9
194,2024-07-13,25.9,42.8,9.7,1.7,Sunny,6
199,2024-07-18,19.3,69.2,3.6,1.2,Sunny,1

In [9]:
data[data["Condition"] .str.contains("Sunny")].tail(10)

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),Rainfall (mm),Condition,UV Index
173,2024-06-22,26.7,81.1,3.6,0.9,Sunny,10
175,2024-06-24,29.1,44.1,5.7,2.0,Sunny,8
177,2024-06-26,32.3,89.3,4.8,2.2,Sunny,8
178,2024-06-27,23.7,58.7,3.2,0.4,Sunny,4
182,2024-07-01,19.6,89.3,8.9,0.2,Sunny,5
184,2024-07-03,23.9,58.8,11.8,1.4,Sunny,4
186,2024-07-05,27.4,78.9,1.3,0.1,Sunny,9
190,2024-07-09,22.8,45.6,6.5,0.5,Sunny,9
194,2024-07-13,25.9,42.8,9.7,1.7,Sunny,6
199,2024-07-18,19.3,69.2,3.6,1.2,Sunny,1

In [15]:
data[(data["Condition"]== "Sunny") | (data["Wind Speed (km/h)"] < 10)]

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),Rainfall (mm),Condition,UV Index
1,2024-01-02,24.3,77.0,5.6,0.3,Rainy,7
2,2024-01-03,28.2,74.9,4.3,0.6,Stormy,1
3,2024-01-04,32.6,75.1,13.0,0.4,Sunny,10
4,2024-01-05,23.8,58.0,3.4,0.4,Foggy,6
6,2024-01-07,32.9,80.5,0.2,0.4,Cloudy,3
...,...,...,...,...,...,...,...
194,2024-07-13,25.9,42.8,9.7,1.7,Sunny,6
195,2024-07-14,26.9,45.9,8.6,0.1,Cloudy,1
196,2024-07-15,20.6,45.9,5.3,3.0,Foggy,3
198,2024-07-17,25.3,77.3,9.1,1.5,Foggy,6
199,2024-07-18,19.3,69.2,3.6,1.2,Sunny,1

In [27]:
data[((data["Condition"] == "Sunny") & (data["Wind Speed (km/h)"] > 10)) | (data["UV Index"] > 5)]

,Date,Temperature (C),Humidity (%),Wind Speed (km/h),Rainfall (mm),Condition,UV Index
1,2024-01-02,24.3,77.0,5.6,0.3,Rainy,7
3,2024-01-04,32.6,75.1,13.0,0.4,Sunny,10
4,2024-01-05,23.8,58.0,3.4,0.4,Foggy,6
7,2024-01-08,28.8,80.5,14.5,4.5,Cloudy,6
10,2024-01-11,22.7,65.6,7.9,1.1,Stormy,10
...,...,...,...,...,...,...,...
190,2024-07-09,22.8,45.6,6.5,0.5,Sunny,9
191,2024-07-10,29.3,64.6,1.9,0.4,Foggy,9
192,2024-07-11,26.1,40.6,4.3,0.1,Cloudy,10
194,2024-07-13,25.9,42.8,9.7,1.7,Sunny,6
198,2024-07-17,25.3,77.3,9.1,1.5,Foggy,6

In [ ]:
#----------------------------------------------------------------------